http:
  routers:
    firefly-rtr:
      rule: "Host(`firefly.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-authelia@file
      service: firefly-svc
      tls:
        certResolver: dns-cloudflare
  services:
    firefly-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.5.8:8095"
