http:
  routers:
    pihole-rtr:
      rule: "Host(`pihole.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-authelia@file
      service: pihole-svc
      tls:
        certResolver: dns-cloudflare
  services:
    pihole-svc:
      loadBalancer:
        servers:
#          - url: "http://{{env "SERVER_LAN_IP"}}:9000" # Or, "http://portainer:9000" if Portainer is part of t3_proxy network
          - url: "http://pihole:8081"
