http:
  routers:
    guacamole-rtr:
      rule: "Host(`guac.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-authelia@file
      service: guacamole-svc
      tls:
        certResolver: dns-cloudflare
  services:
    guacamole-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.5.7:8083"
