http:
  routers:
    wallabag-rtr:
      rule: "Host(`wallabag.{{env "DOMAINNAME"}}`)"
      entryPoints:
        - websecure-internal
        - websecure-external
      middlewares:
        - chain-no-auth@file
      service: wallabag-svc
      tls:
        certResolver: dns-cloudflare
  services:
    wallabag-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.5.8:8089"
